services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    stdin_open: true
    tty: true

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - server